// Copyright 2023 lichangao(李长傲) <changao.li.work@outlook.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/changaolee/skeleton.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: skeleton/v1/skeleton.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Skeleton_ListUser_FullMethodName = "/v1.Skeleton/ListUser"
)

// SkeletonClient is the client API for Skeleton service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkeletonClient interface {
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type skeletonClient struct {
	cc grpc.ClientConnInterface
}

func NewSkeletonClient(cc grpc.ClientConnInterface) SkeletonClient {
	return &skeletonClient{cc}
}

func (c *skeletonClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, Skeleton_ListUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkeletonServer is the server API for Skeleton service.
// All implementations must embed UnimplementedSkeletonServer
// for forward compatibility
type SkeletonServer interface {
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedSkeletonServer()
}

// UnimplementedSkeletonServer must be embedded to have forward compatible implementations.
type UnimplementedSkeletonServer struct {
}

func (UnimplementedSkeletonServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedSkeletonServer) mustEmbedUnimplementedSkeletonServer() {}

// UnsafeSkeletonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkeletonServer will
// result in compilation errors.
type UnsafeSkeletonServer interface {
	mustEmbedUnimplementedSkeletonServer()
}

func RegisterSkeletonServer(s grpc.ServiceRegistrar, srv SkeletonServer) {
	s.RegisterService(&Skeleton_ServiceDesc, srv)
}

func _Skeleton_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkeletonServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Skeleton_ListUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkeletonServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Skeleton_ServiceDesc is the grpc.ServiceDesc for Skeleton service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Skeleton_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Skeleton",
	HandlerType: (*SkeletonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _Skeleton_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skeleton/v1/skeleton.proto",
}
