# Copyright 2023 lichangao(李长傲) <changao.li.work@outlook.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/changaolee/skeleton.

# REST 服务配置
server:
  mode: debug # 可选值 release, debug, test
  healthz: true # 是否开启健康检查，如果开启会安装 /healthz 路由
  middlewares: recovery,secure,nocache,cors,dump # 加载的 gin 中间件列表，多个中间件，逗号(,)隔开
  max-ping-count: 3 # http 服务启动后，自检尝试次数，默认 3

# HTTP 相关配置
insecure:
  bind-address: 127.0.0.1
  bind-port: 8080

# HTTPS 相关配置
secure:
  bind-address: 0.0.0.0
  bind-port: 8443
  tls:
    cert-key:
      cert-file: ./_output/cert/skt-apiserver.pem  # 签名证书
      private-key-file: ./_output/cert/skt-apiserver-key.pem  # 私钥

# MySQL 数据库相关配置
mysql:
  host: 127.0.0.1  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  username: root  # MySQL 用户名(建议授权最小权限集)
  password: SKT1826!z$  # MySQL 用户密码
  database: skeleton  # skeleton 系统所用的数据库名
  max-idle-connections: 100  # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100  # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s  # 空闲连接最大存活时间，默认 10s
  log-level: 4  # GORM log level, 1: silent, 2:error, 3:warn, 4:info

# 日志配置
log:
  disable-caller: false  # 是否禁止 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-stacktrace: false  # 是否禁止在 panic 及以上级别打印堆栈信息
  level: debug  # 日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  format: json  # 日志显示格式，可选值：console, json
  output-paths: [ stdout ]  # 日志输出位置

# JWT 配置
jwt:
  realm: JWT  # jwt 标识
  key: BHpZUtWXhQM2f09bLcPLLoRB6yCEX04IpyXKZD3DxwU  # 服务端密钥
  timeout: 24h  # token 过期时间(小时)
  max-refresh: 24h  # token 更新时间(小时)