apiVersion: v1
user:
  #token: # JWT Token
  username: admin # skt 用户名
  password: admin123 # skt 密码
  #secret-id: # 密钥 ID
  #secret-key: # 密钥 Key
  client-certificate: ./_output/cert/admin.pem # 用于 TLS 的客户端证书文件路径
  client-key: ./_output/cert/admin-key.pem # 用于 TLS 的客户端 key 文件路径
  #client-certificate-data:
  #client-key-data:

server:
  address: https://127.0.0.1:8443 # skt api-server 地址
  timeout: 10s # 请求 api-server 超时时间
  #max-retries: # 最大重试次数，默认为 0
  #retry-interval: # 重试间隔，默认为 1s
  #tls-server-name: # TLS 服务器名称
  #insecure-skip-tls-verify: # 设置为 true 表示跳过 TLS 安全验证模式，将使得 HTTPS 连接不安全
  certificate-authority: ./_output/cert/ca.pem # 用于 CA 授权的 cert 文件路径
  #certificate-authority-data:
